# The application.properties file contains overall configuration for the Spring Boot application
# It is organized as key-value pairs
# You need one for EACH value you wish to set -- no nesting, no reuse

spring.application.name=my-first-spring-project
spring.application.version=1.0.0
