# You can configure your properties file as a YAML file also if you prefer
# Make sure you use spaces at the beginning! Not tabs!

spring:
  application:
    name: my-first-spring-project
    version: 1.0.0
  output:
    ansi:
      enabled: always
  # this is the setup for our DataSource bean, connecting us automatically to the database
  # it can be filled in with different values for different environments, which we'll see later
  datasource:
  # url: jdbc:postgresql://localhost:5432/school -- yours!
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # driver-class-name: org.postgresql.Driver -- this can be optionally added if you want to explicitly specify the driver
  
  # this allows us to dictate whether changes in our app code will alter the database schema
  # valid values are: none, validate, update, create, create-drop
  jpa:
    hibernate:
      ddl-auto: none
  config:
    import: optional:file:.env[.properties]
    # this allows us to use the .env imports we're using for url, username and password above
    # we no longer post actual values to our repo, just the slugs, and it fills in from the .env file

# the default port for a Spring Boot app is 8080, but you can change to whatever you want within a valid port range
server:
  port: 8080

# customizing the logging level
# root will set the level for the OVERALL application
# you can then choose specific packages and/or classes to dial in
logging:
  level:
    root: INFO
    '[com.skillstorm.controllers]': DEBUG
    # '[com.skillstorm.controllers.SubjectController]': ERROR   # more specific mappings override less specific ones

# setup for actuator
management:
  endpoints:
    web:
      # base-path: /mgmt # can change root path, defaults to /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always