# this configuration file will be active ONLY when we're using the prod profile
# all we have to do is name the file in this way -- application-<name of profile>
duplicate:
    key: PROD Profile Active!