INSERT INTO counselor (first_name, last_name) VALUES ('Hardy', 'De Vries');
INSERT INTO counselor (first_name, last_name) VALUES ('Venita', 'Huffadine');
INSERT INTO counselor (first_name, last_name) VALUES ('Claudine', 'Rosborough');
INSERT INTO counselor (first_name, last_name) VALUES ('Steffie', 'Wells');
INSERT INTO counselor (first_name, last_name) VALUES ('Paten', 'Pentycross');
INSERT INTO counselor (first_name, last_name) VALUES ('Finley', 'Garrity');
INSERT INTO counselor (first_name, last_name) VALUES ('Elisa', 'Annon');
INSERT INTO counselor (first_name, last_name) VALUES ('Tory', 'Scrimgeour');
INSERT INTO counselor (first_name, last_name) VALUES ('Melina', 'Devonish');
INSERT INTO counselor (first_name, last_name) VALUES ('Bryn', 'McKennan');

INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lorens', 'Thebe', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Almira', 'Pestricke', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nedi', 'Di Nisco', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ernestus', 'Gowler', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nikkie', 'Aspling', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Martelle', 'Daddow', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Aimee', 'Dendle', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Gilberte', 'Aiskovitch', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Dolores', 'Janoch', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Gar', 'Flook', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Shirlee', 'Pepper', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Aeriela', 'Fawcett', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Else', 'Ovize', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Emeline', 'Eveling', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Clementia', 'Richly', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Red', 'Relf', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nicoline', 'Harfleet', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Mandel', 'Andrivot', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Antoine', 'Corinton', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Kristin', 'Garric', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Melisenda', 'Bartolomeazzi', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Gawen', 'Lassells', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ellene', 'Accum', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lanny', 'Hulstrom', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Conney', 'McElree', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Kathrine', 'Sebire', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Bendite', 'Riall', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Mollee', 'Ambroz', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Isabeau', 'Diggles', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Donnajean', 'Mussalli', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Kirby', 'Fenech', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lind', 'Sarre', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nicol', 'Child', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Verney', 'Basso', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Terrell', 'Luesley', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Chico', 'Djordjevic', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Judd', 'Ford', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Guendolen', 'Huonic', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Derron', 'Poe', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Derby', 'Jozsa', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Paxton', 'Schechter', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Allene', 'Klaffs', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lishe', 'Baribal', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Bathsheba', 'Haggard', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Cati', 'Burgan', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lin', 'Kitlee', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Jeremiah', 'Elsby', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Dolly', 'Dixey', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Lucais', 'Duerden', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Gannon', 'Bandt', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Rick', 'Blaze', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Rhea', 'Myles', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Dennie', 'Dilon', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Evanne', 'Gurnett', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Conchita', 'Ginn', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Roobbie', 'Esh', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Bartram', 'Greenless', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Fonz', 'Ballister', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Rayshell', 'Paolotto', 7);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Dixie', 'Janczewski', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ginnie', 'McGown', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Minnaminnie', 'Twiname', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Petronia', 'Maryska', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Rodrique', 'Andrey', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nichole', 'Storie', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Archie', 'Evemy', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ravi', 'Christon', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ailis', 'Tease', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Weylin', 'Haggarth', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Celia', 'Pfeiffer', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Dorotea', 'Eastam', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Isa', 'Croote', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Waldemar', 'Bryer', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Gerik', 'Barney', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Orren', 'Trevorrow', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Jsandye', 'Cottey', 5);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Bernette', 'Lapwood', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Valma', 'Filkov', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Nappie', 'Bednell', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ugo', 'Edon', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Cyril', 'Godby', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Catarina', 'Le Sieur', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Manda', 'Kasman', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Heinrick', 'Dumbellow', 8);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Mellisent', 'Churms', 4);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Blair', 'Vauls', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ogdan', 'Noir', 10);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Sammy', 'Marrian', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Alva', 'Cromleholme', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Antonius', 'Lawrie', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Tracee', 'Scolding', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Eduino', 'Mackin', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Baldwin', 'Elderfield', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Markus', 'Gergher', 3);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Didi', 'Blakeman', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Reggy', 'Fosken', 2);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Danny', 'O''Ferris', 9);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Krishnah', 'Scotson', 6);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Fayina', 'Bartusek', 1);
INSERT INTO student (first_name, last_name, counselor_id) VALUES ('Ogdon', 'Inch', 4);

INSERT INTO subject (title) VALUES ('Math');
INSERT INTO subject (title) VALUES ('English');
INSERT INTO subject (title) VALUES ('Science');
INSERT INTO subject (title) VALUES ('Physical Education');
INSERT INTO subject (title) VALUES ('Java');

INSERT INTO teacher (first_name, last_name, subject_id) VALUES ('Joel', 'Bernardotte', 1);
INSERT INTO teacher (first_name, last_name, subject_id) VALUES ('Drusilla', 'Spurdle', 2);
INSERT INTO teacher (first_name, last_name, subject_id) VALUES ('Solly', 'McGinney', 3);
INSERT INTO teacher (first_name, last_name, subject_id) VALUES ('Spence', 'Schnieder', 4);
INSERT INTO teacher (first_name, last_name, subject_id) VALUES ('Blondy', 'Wike', 5);

INSERT INTO enrollment (student_id, subject_id) VALUES (22, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (68, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (69, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (82, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (83, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (25, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (62, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (98, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (47, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (65, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (46, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (59, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (8, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (38, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (19, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (94, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (76, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (87, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (12, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (56, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (39, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (87, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (87, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (83, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (89, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (9, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (9, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (63, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (64, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (16, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (32, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (64, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (29, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (75, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (79, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (71, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (65, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (34, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (99, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (69, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (86, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (32, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (88, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (28, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (79, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (10, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (82, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (26, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (14, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (32, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (55, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (33, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (13, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (27, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (55, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (66, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (94, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (34, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (57, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (1, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (52, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (47, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (58, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (81, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (17, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (79, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (34, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (14, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (95, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (75, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (91, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (2, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (36, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (62, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (42, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (81, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (61, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (89, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (60, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (91, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (26, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (87, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (62, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (25, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (41, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (86, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (26, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (68, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (47, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (85, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (46, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (52, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (30, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (22, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (71, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (48, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (97, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (81, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (90, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (70, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (67, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (40, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (43, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (100, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (99, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (30, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (58, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (27, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (32, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (36, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (55, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (72, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (75, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (84, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (72, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (30, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (46, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (12, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (20, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (93, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (53, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (63, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (15, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (67, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (16, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (22, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (15, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (29, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (48, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (44, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (95, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (56, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (1, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (11, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (4, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (53, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (71, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (60, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (18, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (99, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (47, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (82, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (54, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (9, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (2, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (68, 2);
INSERT INTO enrollment (student_id, subject_id) VALUES (87, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (19, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (98, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (38, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (27, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (84, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (78, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (38, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (49, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (77, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (16, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (76, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (18, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (40, 5);
INSERT INTO enrollment (student_id, subject_id) VALUES (83, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (96, 1);
INSERT INTO enrollment (student_id, subject_id) VALUES (76, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (84, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (29, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (24, 3);
INSERT INTO enrollment (student_id, subject_id) VALUES (20, 4);
INSERT INTO enrollment (student_id, subject_id) VALUES (15, 4);