package com.skillstorm.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// an Entity IS NOT A BEAN!
// Beans will come later with repos/services/controllers

// this class is an entity representing objects of our artist table in the DB
// one instance of this class = one row in the artist table
@Entity                     // this class represents a DB table
@Table(name = "artist")     // this specifies the name of the table in the database; if the same as the class, this can be omitted
public class Artist {

    @Id                             // this property is the PK for the table
    @Column(name = "artistid")      // this property connects to a column; like with Table, if they match, you can leave the name part off
    @GeneratedValue(strategy = GenerationType.IDENTITY) // this property's value is automatically generated by the database and auto-increments
    private int id;

    @Column(name = "name")
    private String name;

    public Artist() {
    }

    public Artist(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    } 

}