package com.skillstorm.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// an Entity IS NOT A BEAN!
// Beans will come later with repos/services/controllers

// this class is an entity representing objects of our artist table in the DB
// one instance of this class = one row in the artist table
@Entity                     // this class represents a DB table
@Table(name = "counselor")     // this specifies the name of the table in the database; if the same as the class, this can be omitted
public class Counselor {

    @Id                             // this property is the PK for the table
    // @Column(name = "id")      // this property connects to a column; like with Table, if they match, you can leave the name part off
    @GeneratedValue(strategy = GenerationType.IDENTITY) // this property's value is automatically generated by the database and auto-increments
    private int id;

    @Column(name = "first_name") // this technically matches as well and is unnecessary, but having it doesn't hurt
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    public Counselor() {
    }

    public Counselor(int id, String firstName, String lastName) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

}